name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.2, 8.1, 8.0, 7.4]
        laravel: [11.*, 10.*, 9.*, 8.*]
        statamic: [5.*, 4.*, 3.*]
        dependency-version: [prefer-stable]
        os: [ubuntu-latest]
        include:
          - laravel: 11.*
            testbench: 8.*
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.*
        exclude:
          - laravel: 9.*
            statamic: ^3.2
          - laravel: 9.* 
            php: 7.4
          - laravel: 10.*
            php: 8.0
          - laravel: 10.*
            php: 7.4

    name: P${{ matrix.php }} - S${{ matrix.statamic }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" ${{ matrix.additional-deps }} --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - name: Run PHPUnit
        run: composer test
